// src/lib/components/PropertyCard.svelte
<script lang="ts">
	import SecureImage from './SecureImage.svelte';

	export let business: {
		name: string;
		category: string;
		city: string;
		state: string;
		country: string;
		publicId: string;
		images: {
			position: number;
			objectName: string;
		}[];
	};
</script>

<a href={`/business/${business.publicId}`} class="property-card">
	{#if business?.images?.length > 0 && business.images[0]?.objectName}
		<SecureImage
			src="{import.meta.env.VITE_IMAGE_URL}/{business.images[0].objectName}"
			alt={business.name}
			width={600}
			height={400}
			className="h-48 w-full rounded-t object-cover"
			on:error={(e) => ((e.currentTarget as HTMLImageElement).src = '/image-placeholder.svg')}
		/>
	{:else}
		<img
			src="/image-placeholder.svg"
			alt="No image available"
			class="h-48 w-full rounded-t object-cover"
		/>
	{/if}

	<div class="details">
		<div class="price-type">
			<h3>{business.name}</h3>
			<span class="price">{business.category}</span>
		</div>
		<p class="location">{business.city}, {business.state}, {business.country}</p>
	</div>
</a>

<style>
	.property-card {
		display: block;
		text-decoration: none;
		color: inherit;
		border-radius: 12px;
		overflow: hidden;
		transition: transform 0.2s;
		box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
		background: white;

		&:hover {
			transform: translateY(-4px);
			box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
		}

		img {
			width: 100%;
			height: 200px;
			object-fit: cover;
		}

		.details {
			padding: 1rem;

			.price-type {
				display: flex;
				justify-content: space-between;
				align-items: center;
				margin-bottom: 0.5rem;

				.price {
					font-weight: bold;
					color: #ff5a5f;
				}
			}

			.location {
				color: #666;
				margin-bottom: 0.5rem;
				font-size: 0.9rem;
			}
		}
	}
</style>

// components/PropertyCard.tsx
// src/components/PropertyCard.tsx
'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';

interface BusinessImage {
    position: number;
    objectName: string;
}

interface Business {
    name: string;
    category: string;
    city: string;
    state: string;
    country: string;
    publicId: string;
    images: BusinessImage[];
}

interface PropertyCardProps {
    business: Business;
}

export default function PropertyCard({ business }: PropertyCardProps) {
    const [imageSrc, setImageSrc] = useState<string>(
        business?.images?.length > 0 && business.images[0]?.objectName
            ? business.images[0].objectName
            : '/static/image-placeholder.svg'
    );

    const handleImageError = () => {
        setImageSrc('/static/image-placeholder.svg');
    };

    return (
        <Link
            href={`/business/${business.publicId}`}
            className="block no-underline text-inherit rounded-xl overflow-hidden transition-transform duration-200 shadow-md hover:shadow-xl hover:-translate-y-1 bg-white"
        >
            <div className="w-full h-48">
                <Image
                    src={imageSrc}
                    alt={business.name}
                    width={400}
                    height={200}
                    className="w-full h-full object-cover"
                    onError={handleImageError}
                    loading='lazy'
                />
            </div>
            <div className="p-4">
                <div className="flex justify-between items-center mb-2">
                    <h3 className="text-lg font-semibold">{business.name}</h3>
                    <span className="font-bold text-red-500">{business.category}</span>
                </div>
                <p className="text-gray-600 text-sm mb-2">
                    {business.city}, {business.state}, {business.country}
                </p>
            </div>
        </Link>
    );
}
